# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lightness.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lightnessDialog(object):
    def setupUi(self, lightnessDialog):
        lightnessDialog.setObjectName("lightnessDialog")
        lightnessDialog.resize(1141, 461)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(lightnessDialog.sizePolicy().hasHeightForWidth())
        lightnessDialog.setSizePolicy(sizePolicy)
        lightnessDialog.setMinimumSize(QtCore.QSize(1141, 461))
        lightnessDialog.setMaximumSize(QtCore.QSize(1141, 461))
        self.frame = QtWidgets.QFrame(lightnessDialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1121, 51))
        self.frame.setStyleSheet("QFrame#frame{\n"
"border-radius: 4px;\n"
"border: 2px solid rgb(229, 229, 229);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(10, 0, 401, 41))
        self.label_15.setStyleSheet("color: #FFF;\n"
"font: 75 20pt \"Berlin Sans FB Demi\";")
        self.label_15.setTextFormat(QtCore.Qt.PlainText)
        self.label_15.setObjectName("label_15")
        self.close_button = QtWidgets.QPushButton(self.frame)
        self.close_button.setGeometry(QtCore.QRect(1090, 20, 17, 17))
        self.close_button.setMinimumSize(QtCore.QSize(16, 16))
        self.close_button.setMaximumSize(QtCore.QSize(17, 17))
        self.close_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.close_button.setText("")
        self.close_button.setObjectName("close_button")
        self.minimize_button = QtWidgets.QPushButton(self.frame)
        self.minimize_button.setGeometry(QtCore.QRect(1060, 20, 17, 17))
        self.minimize_button.setMinimumSize(QtCore.QSize(16, 16))
        self.minimize_button.setMaximumSize(QtCore.QSize(17, 17))
        self.minimize_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.minimize_button.setText("")
        self.minimize_button.setObjectName("minimize_button")
        self.frame_2 = QtWidgets.QFrame(lightnessDialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 70, 1121, 381))
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"border-radius: 4px;\n"
"border: 2px solid rgb(229, 229, 229);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.image_label = QtWidgets.QLabel(self.frame_2)
        self.image_label.setGeometry(QtCore.QRect(560, 30, 550, 340))
        self.image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image_label.setText("")
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.tabs = QtWidgets.QTabWidget(self.frame_2)
        self.tabs.setGeometry(QtCore.QRect(10, 10, 541, 361))
        self.tabs.setWhatsThis("")
        self.tabs.setObjectName("tabs")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.slider1_counter = QtWidgets.QLabel(self.tab_3)
        self.slider1_counter.setGeometry(QtCore.QRect(70, 30, 31, 31))
        self.slider1_counter.setTextFormat(QtCore.Qt.AutoText)
        self.slider1_counter.setObjectName("slider1_counter")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(60, 290, 51, 21))
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setObjectName("label_11")
        self.apply_button_2 = QtWidgets.QPushButton(self.tab_3)
        self.apply_button_2.setEnabled(True)
        self.apply_button_2.setGeometry(QtCore.QRect(412, 290, 101, 28))
        self.apply_button_2.setObjectName("apply_button_2")
        self.slider1 = QtWidgets.QSlider(self.tab_3)
        self.slider1.setGeometry(QtCore.QRect(60, 60, 31, 221))
        self.slider1.setMinimum(0)
        self.slider1.setMaximum(300)
        self.slider1.setSingleStep(1)
        self.slider1.setTracking(True)
        self.slider1.setOrientation(QtCore.Qt.Vertical)
        self.slider1.setObjectName("slider1")
        self.slider2_counter = QtWidgets.QLabel(self.tab_3)
        self.slider2_counter.setGeometry(QtCore.QRect(140, 30, 31, 31))
        self.slider2_counter.setTextFormat(QtCore.Qt.AutoText)
        self.slider2_counter.setObjectName("slider2_counter")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(130, 290, 61, 21))
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setObjectName("label_12")
        self.slider2 = QtWidgets.QSlider(self.tab_3)
        self.slider2.setGeometry(QtCore.QRect(130, 60, 31, 221))
        self.slider2.setMinimum(0)
        self.slider2.setMaximum(100)
        self.slider2.setSingleStep(1)
        self.slider2.setTracking(True)
        self.slider2.setOrientation(QtCore.Qt.Vertical)
        self.slider2.setObjectName("slider2")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(200, 290, 71, 21))
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setObjectName("label_13")
        self.slider3 = QtWidgets.QSlider(self.tab_3)
        self.slider3.setGeometry(QtCore.QRect(200, 60, 31, 221))
        self.slider3.setMinimum(0)
        self.slider3.setMaximum(100)
        self.slider3.setSingleStep(1)
        self.slider3.setTracking(True)
        self.slider3.setOrientation(QtCore.Qt.Vertical)
        self.slider3.setObjectName("slider3")
        self.slider3_counter = QtWidgets.QLabel(self.tab_3)
        self.slider3_counter.setGeometry(QtCore.QRect(210, 30, 31, 31))
        self.slider3_counter.setTextFormat(QtCore.Qt.AutoText)
        self.slider3_counter.setObjectName("slider3_counter")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(280, 290, 41, 21))
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setObjectName("label_14")
        self.slider4_counter = QtWidgets.QLabel(self.tab_3)
        self.slider4_counter.setGeometry(QtCore.QRect(290, 30, 31, 31))
        self.slider4_counter.setTextFormat(QtCore.Qt.AutoText)
        self.slider4_counter.setObjectName("slider4_counter")
        self.slider4 = QtWidgets.QSlider(self.tab_3)
        self.slider4.setGeometry(QtCore.QRect(280, 60, 31, 221))
        self.slider4.setMinimum(1)
        self.slider4.setMaximum(200)
        self.slider4.setSingleStep(1)
        self.slider4.setTracking(True)
        self.slider4.setOrientation(QtCore.Qt.Vertical)
        self.slider4.setObjectName("slider4")
        self.tabs.addTab(self.tab_3, "")

        self.retranslateUi(lightnessDialog)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(lightnessDialog)

    def retranslateUi(self, lightnessDialog):
        _translate = QtCore.QCoreApplication.translate
        lightnessDialog.setWindowTitle(_translate("lightnessDialog", "Add Noise"))
        self.label_15.setText(_translate("lightnessDialog", "调整图像亮度"))
        self.slider1_counter.setText(_translate("lightnessDialog", "0"))
        self.label_11.setText(_translate("lightnessDialog", "亮度"))
        self.apply_button_2.setText(_translate("lightnessDialog", "应用效果"))
        self.slider2_counter.setText(_translate("lightnessDialog", "0"))
        self.label_12.setText(_translate("lightnessDialog", "对比度"))
        self.label_13.setText(_translate("lightnessDialog", "饱和度"))
        self.slider3_counter.setText(_translate("lightnessDialog", "0"))
        self.label_14.setText(_translate("lightnessDialog", "色温"))
        self.slider4_counter.setText(_translate("lightnessDialog", "0"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), _translate("lightnessDialog", "Periodic"))
    def getComponents(self):
        return [self.tabs,
                self.slider1, self.slider2, self.slider3, self.slider4,
                self.slider1_counter, self.slider2_counter, self.slider3_counter, self.slider4_counter,
                self.apply_button_2, ]